### ISSUE TITLE
flipping back and forth > 2 times between a page back to Alien breaks

### ISSUE THREAD

**Issue by brandiweekes** [brandiweekes/HawkBox#2]
In the menu window, bug presents itself in the following steps:

click Alien in menu
click any other page in menu
click Alien in menu 
X break!

```
System.Runtime.InteropServices.COMException
  HResult=0x800F1000
  Message=No installed components were detected.

Element is already the child of another element.
  Source=Windows
  StackTrace:
   at Windows.UI.Xaml.Controls.ContentControl.put_Content(Object value)
   at Xamarin.Forms.Platform.UWP.ScrollViewRenderer.UpdateContent()
   at Xamarin.Forms.Platform.UWP.ScrollViewRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.SetupVisualElement(VisualElement view)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.OnChildAdded(Object sender, ElementEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Xamarin.Forms.Element.OnChildAdded(Element child)
   at Xamarin.Forms.VisualElement.OnChildAdded(Element child)
   at Xamarin.Forms.Page.OnInternalAdded(VisualElement view)
   at Xamarin.Forms.Page.InternalChildrenOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Xamarin.Forms.TemplateUtilities.OnContentChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value)
   at Crawl.Views.CharactersPage.InitializeComponent() in C:\Repos\5250HawkBox\Crawl\Crawl.UWP\obj\x86\Debug\Views\Characters\CharactersPage.xaml.g.cs:line 30
   at Crawl.Views.CharactersPage.OnAppearing() in C:\Repos\5250HawkBox\Crawl\Crawl\Views\Characters\CharactersPage.xaml.cs:line 48
   at Xamarin.Forms.Page.SendAppearing()
   at Xamarin.Forms.Page.SendAppearing()
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.OnLoaded(Object sender, RoutedEventArgs args)
```

**Comment by brandiweekes** [comment]
a ListView is a ScrollViewer, so don't want to have both;
```
<ScrollView>
    <ListView/>
</ScrollView>
```

just remove
`<ScrollView/>`
